#
# Cost map common parameters
#
map_type:       costmap

obstacle_range: 5.0     # was 0.0,  (double, default 2.5) The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters. This can be over-ridden on a per-sensor basis.
raytrace_range: 8.0     # was 0.0,  (double, default 3.0) The default range in meters at which to raytrace out obstacles from the map using sensor data. This can be over-ridden on a per-sensor basis.

#
# laser scanner section
#
observation_sources: laser_scan_sensor
laser_scan_sensor:   {sensor_frame: hokuyo, data_type: LaserScan, topic: /doug_bot/laser/scan, marking: true, clearing: true}

