#
# Global cost map
#
global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10.0              # was 50.0, The frequency in Hz for the map to be updated.
   publish_frequency: 10.0             # was 50.0, The frequency in Hz for the map to be publish display information.
   width: 40.0                         # The width of the map in meters.
   height: 40.0                        # The height of the map in meters.
   resolution: 0.02                    # The resolution of the map in meters/cell. Hokuyo URG-04LX-UG01 laser scanner has metric resolution of 0.01mm
   static_map: true
   rolling_window: false               # Whether or not to use a rolling window version of the costmap. If the static_map parameter is set to true, this parameter must be set to false.

